### ISSUE TITLE
Github Flow

### ISSUE THREAD

**Issue by partikus** [PGS-php/upskilling-2nd-edition#8]
@PGS-php/php-rze @dominikhajduk @tarnawski I suggest to use github forks and [github flow](https://guides.github.com/activities/forking/)

**Comment by dominikhajduk** [comment]
👍 for newly created branches

**Comment by dominikhajduk** [comment]
Will that be enough: https://github.com/PGS-php/upskilling-2nd-edition/pull/14 ?
